# Generated by Django 2.0.dev20170308171458 on 2018-04-26 12:14

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_invoices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice',
            field=models.ImageField(default=0, upload_to=projects.models.get_image_path),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprojectrights',
            name='project',
        ),
        migrations.AddField(
            model_name='userprojectrights',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
    ]
