# Generated by Django 2.0.dev20170308171458 on 2018-05-15 12:36

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180426_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='bicc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='iban',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice',
            field=models.FileField(upload_to=projects.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
